build:
  cuda_version: "12.1.1"
  system_packages:
    - "libssl-dev"
  python_packages:
    - "accelerate==0.26.1"
    - "torch==2.2.1"
    - "transformers==4.36.2"
    - "bitsandbytes==0.42.0"
    - "-e git+https://github.com/huggingface/peft.git#egg=peft"
    - "hf-transfer==0.1.9"
    - "huggingface-hub==0.29.1"
    - "sentencepiece==0.2.0"
